all: serverA.cpp serverB.cpp serverC.cpp serverM.cpp client.cpp monitor.cpp
		g++ -o serverA serverA.cpp

		g++ -o serverB serverB.cpp

		g++ -o serverC serverC.cpp

		g++ -o serverM serverM.cpp

		g++ -o client client.cpp

		g++ -o monitor monitor.cpp
